### ISSUE TITLE
how do you set a custom structure as the thing to be generated?

### ISSUE THREAD

**Issue by AlexanderwithaA** [gniftygnome/skylark#1]
I'm having issues figuring out how to get skylark to generate a custom structure I made, it was made with a structure block so is in .nbt file. Any help with making it generate would be appreciated.

**Comment by gniftygnome** [comment]
You need to register it with Minecraft.  Switch to Creative mode and make sure you can see it in the completions for `/place structure`.  When adding an nbt structure to the game via a datapack, you will need json files in `worldgen/structure` and `worldgen/template_pool`.  The nbt itself goes in `structures`.

https://misode.github.io/worldgen/structure/
https://misode.github.io/worldgen/template-pool/

See also:  https://misode.github.io/guides/adding-custom-structures/

If you do see it in place structure but it is not appearing when configured, the odds are good the structure has some requirement such as having a world surface to place on.  That is why many of the vanilla structures either do not appear or appear in a fairly cursed manner down at the bottom of the world when configured in Skylark.

**Comment by AlexanderwithaA** [comment]
Is this for 1.19+? I'm running 1.18.2, theres no section for worldgen/structure

**Comment by gniftygnome** [comment]
Version 0.2.0 was for 1.18.2, but structure generation first became available in 1.0.0-beta.1 for Minecraft 1.20.1.  There were some changes in the late 1.19 series and in 1.20 that made it easier to place a structure while spawning a player.

**Comment by AlexanderwithaA** [comment]
cleaning up contribs.
