### ISSUE TITLE
Islands not generating

### ISSUE THREAD

**Issue by joshuax8** [gniftygnome/skylark#4]
Hello,
I was trying this mod (version 1.3.0) out on a MC 1.21 Fabric 0.15.11 server and the spawn Islands don't seem to spawn, only the (random) tree.
Is this expected behaviour (if so, how do I spawn the island?).
Thanks!

**Comment by gniftygnome** [comment]
Yes, the default configuration is a random vanilla tree.  See the `spawnPlatform` section of the configuration docs here:
https://github.com/gniftygnome/skylark/wiki/Configuration

f.e.
```
spawnPlatform = ["skylark:sky_island_small"]
```

This is server-side configuration, so if you are playing client-side you may need to start Minecraft, then exit, edit the config file, and start Minecraft again.

**Comment by joshuax8** [comment]
Hi, Thanks for the fast reply, I did try that however when I try that, nothing generates and I just fall in the void as soon as I spawn (even after server restart). Any tips on debugging?

**Comment by gniftygnome** [comment]
Could you attach your game log (server side if there is one).

**Comment by joshuax8** [comment]
Here you go (config file also included).
[latest.log](https://github.com/user-attachments/files/16216591/latest.log)
[skylark.toml.txt](https://github.com/user-attachments/files/16216594/skylark.toml.txt)
(had to add the txt extension to the config file to upload it to Github)

**Comment by gniftygnome** [comment]
OK I finally found it.  Fix incoming as 1.3.0.

**Comment by joshuax8** [comment]
Works like a charm! Thanks!
